### PR TITLE
Remove use of GPIO.set_interrupt/3

### LINKED ISSUE #32: Key presses are occasionally triggered twice
After pressing arbitrary keys for a while, every now and then one of the key presses ends up triggering twice. It doesn't matter if the keys are pressed fast or slow, and I have also tried varying the timing between different key presses. It feels like the issue happens more often after a small pause, but that may just be coincidence. The first few occurrences in the sequence in the screenshot seem to happen just after 50 characters, but that may also be coincidence. In the 123, 456, 789 sequence it feels like 1, 7, 5 trigger the most often. I have tried combinations of keys that are not in that group, like 2, 6, 8, and see the same issue of keys triggering twice. I have also tried the keybow on a couple different surfaces to try to eliminate mechanical bouncing of the keys if that was potentially an issue.

image

Is anyone else able to reproduce this?

### PR DESCRIPTION
**Pull request by nickdichev**
Using the built-in `GPIO.set_interrupt/3` function was not so flexible
because we can't tune the `:supress_glitches` parameter.

We ripped out the use of `GPIO.set_interrupt/3` and replaced it with a
custom polling mechanism that reads the pin values and fires off AFK
state updates.

Additionally, we were able to remove a lot of cruft surrounding the
initialization of the Keys `GenServer`.

Co-authored-by: Alex McLain

Resolves #32.

### CODE REVIEW

**Comment by nickdichev** [comment]
@doughsay Why does the Keys GenServer maintain its own `:keyboard_state` in its state, but also AFK is a GenServer that maintains its own state. Does it make sense for AFK to be a purely functional data structure? @amclain and I aren't too familiar with how AFK functions!

**Comment by amclain** [comment]
Resolves #32.

**Comment by amclain** [comment]
@doughsay do you have time to review this PR? There were some major changes to `keys.ex` and it would be nice to have your eyes on it.

**Comment by doughsay** [comment]
> @doughsay Why does the Keys GenServer maintain its own `:keyboard_state` in its state, but also AFK is a GenServer that maintains its own state. Does it make sense for AFK to be a purely functional data structure? @amclain and I aren't too familiar with how AFK functions!

`keyboard_state` is not a "keyboard state" per-se, it's just the PID of the AFK process.  Are you proposing starting AFK in the application supervision tree instead?

Yes, AFK used to be a purely functional data structure, and I tried hard to keep it that way.  Nevertheless, it needed to become it's own stateful server in order to support the features I want it to have long-term.

I imagine this whole mess as a series of global event publishers and subscribers: `Keys` is responsible for emitting physical keypress events only.  `AFK` wants to subscribe to those events to mutate its internal keyboard state, which in turn emits one (or more, over time) HID-state change events.  Something else (`HIDServer`?) wants to subscribe to the HID state change events, and send those as HID reports to the host OS.

Right now, `Keys` is basically performing ALL of these functions at once (by way of starting its own AFK server outside of supervision tree).  It's performing the HID functionality by way of `handle_info({:hid_report, hid_report}, ...)` and `AFK.State.start_link(..., event_receiver: self(), ...)`.

I'm up for any way to clean this up to make more sense, please offer suggestions.

**Comment by doughsay** [comment]
> @amclain and I aren't too familiar with how AFK functions!

Really the idea is that you shouldn't have to know, it's a pure black-box that just requires you to call `AFK.State.press_key/2` and and `AFK.State.release_key/2` and it emits appropriate HID events to the `event_receiver` PID given when you started it.  That's all you should know or care about, the internal workings are "magic".

**Comment by doughsay** [comment]
Please let me know if the README (https://github.com/doughsay/afk) is lacking and if I should update it ;)

**Comment by amclain** [comment]
> `keyboard_state` is not a "keyboard state" per-se, it's just the PID of the AFK process.

Ohhhh, that makes sense. `keyboard_state` sounded like we were passing `%KeyboardState{}` to AFK. Maybe `keys.ex` storing `state.afk_pid` would be more clear.

**Comment by doughsay** [comment]
> Ohhhh, that makes sense. `keyboard_state` sounded like we were passing `%KeyboardState{}` to AFK. Maybe `keys.ex` storing `state.afk_pid` would be more clear.

Yeah exactly.  I think possibly the naming of the key was a holdover from when AFK *was* purely functional. It's most definitely wrong now, giving it a name with `pid` in it make a lot more sense.

**Pull request merged**
