### PR TITLE
Use mix upload command from the latest nerves_firmware_ssh

### PR DESCRIPTION
**Pull request by amclain**
Related to #55 

This PR updates us to the cutting edge of `nerves_firmware_ssh` where `mix upload` is being introduced as an official command, and `upload.sh` will no longer be required. I've made a couple other tweaks to our `mix.exs` file to accommodate for some xebow-specific conveniences.

I plan on keeping this an open PR until `mix upload` makes it into a release, unless you all feel differently.

## Steps for testing

- Check out this branch
  - `refactor/nerves_firmware_ssh-upload`
- Update dependencies
  - `MIX_TARGET=keybow mix deps.get`
- Build the firmware
  - `mix firmware`
- Upload the firmware
  - `mix upload`

### CODE REVIEW

**Comment by vanvoljg** [comment]
Yeah, it works perfectly. Go ahead and merge.

**Comment by doughsay** [comment]
works for me!

**Comment by fhunleth** [comment]
You all are awesome! Thank you for trying it out last night. It's in an official release now: https://hex.pm/packages/nerves_firmware_ssh/0.4.6.

**Comment by amclain** [comment]
Awesome, thanks @fhunleth! :tada:

**Pull request merged**
