### PR TITLE
Update to keybow system v2.0.0-rc.1+keybow.1

### PR DESCRIPTION
**Pull request by amclain**
Depends on ElixirSeattle/nerves_system_keybow#6

This PR updates xebow to the latest system, which pulls in the upstream changes from `rpi0` `v2.0.0-rc.1`.

If you see the following error when building the firmware, update to the latest [`fwup`](https://github.com/fhunleth/fwup) (1.8.1).

```
** (Mix) Nerves encountered an error. %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: true}
```

### CODE REVIEW

**Comment by doughsay** [comment]
Do we need to update the erlang version at all in .tool-versions?  It should match the version built in the customized system right?

**Comment by amclain** [comment]
Good call, I've bumped erlang to `23.1.1` to match the `nerves_system_br` that's being used.

**Review by doughsay — APPROVED** [review]
:tada:

**Review by vanvoljg — APPROVED** [review]
👍🥳

**Pull request merged**
